import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ToastProvider } from "@/components/ui/toast";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function ThemeToggle() {
  if (typeof window === "undefined") return null;
  return (
    <button
      onClick={() => {
        const el = document.documentElement;
        const next = el.classList.contains("dark") ? "light" : "dark";
        el.classList.toggle("dark", next === "dark");
        try {
          localStorage.setItem("theme", next);
        } catch {}
      }}
      className="bg-background fixed bottom-4 left-4 rounded-md border px-3 py-2 text-sm shadow"
    >
      Toggle Theme
    </button>
  );
}

function useInitTheme() {
  if (typeof window === "undefined") return;
  try {
    const stored = localStorage.getItem("theme");
    if (stored) {
      document.documentElement.classList.toggle("dark", stored === "dark");
    }
  } catch {}
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  useInitTheme();
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <ToastProvider>
            {children}
            <ThemeToggle />
          </ToastProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
